### ISSUE TITLE
Enrutar correos a grupo privado

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#10]
Existe un grupo de google para la organización de la geocamp 2018. Estaría bien enrutar una dirección externa `patatas@geocam.es` a ese grupo para que la dirección expuesta sea "compartida" por los miembros de la organización y así evitar cuellos de botella.

**Comment by jsanz** [comment]
he borrado a info@geocamp.es del grupo de google.

**Comment by clds1** [comment]
oh my god!! ahora no llegan los mails ni a info@geocamp.es..... tengo miedo Emiliiiiooooo!!!!

**Comment by fpsampayo** [comment]
No entiendo mucho de google groups. En principio, con la prueba que hice yo, la redirección era correcta, ya que la contestación me la dio el propio google groups. Lo que pasará es que el correo no será tal, sólo un alias que recibiréis en el grupo.  Mientras escribía esto, me confirma @clds1 que ya funciona!

**Comment by fpsampayo** [comment]
Es curioso, me podéis asignar issues pero no puedo cerrarlas :-D

**Comment by jsanz** [comment]
Ya funciona, el grupo necesitaba aceptar mensajes desde el exterior.

**Comment by jsanz** [comment]
@fpsampayo te he metido en el equipo `2018`, ya puedes cerrar issues también :grin:

**Comment by fpsampayo** [comment]
@jsanz Ya tenéis licencia para liarme entonces 😁O por lo menos para intentarlo 🤣
