### ISSUE TITLE
Pensar y organizar actividad para el domingo 21

### ISSUE THREAD

**Issue by ramiroaznar** [geocamp-es/2018#12]
Después de declinar la propuesta inicial por causas legales/seguridad, se ha pensado hacer un tour con profesores universitarios o profesionales relacionados con el arte, historia y/o literatura.

### TBD

- [x] enviar un email a la SGE... esperando respuesta.
- [x] pendiente de un profesor de la UAM que hace tours muy interesantes por Madrid.

**Comment by clds1** [comment]
Posible visita al Reina Sofía para exposición de mapas???

**Comment by clds1** [comment]
Puede ser un complemento a la salida educativa por Madrid....

**Comment by ramiroaznar** [comment]
He vuelto a contactar con el contacto. Para confirmar la actividad. En caso contrario le he comentado la exposicón: http://www.museoreinasofia.es/prensa/nota-de-prensa/luigi-ghirri-mapa-territorio

**Comment by ramiroaznar** [comment]
Diego y Jose dieron un tour fantástico.
