### ISSUE TITLE
añadir imágenes de nuevos sponsors a la web

### ISSUE THREAD

**Issue by ramiroaznar** [geocamp-es/2018#13]
![logo_servigis_vertical](https://user-images.githubusercontent.com/5215798/45819755-6900e880-bce5-11e8-85b8-ae450a0b00f4.png)
![logo_png_x1](https://user-images.githubusercontent.com/5215798/45819758-6a321580-bce5-11e8-88b2-351caf913ce9.png)
![paisajetransversal_logo](https://user-images.githubusercontent.com/5215798/45819759-6acaac00-bce5-11e8-953b-7a38cff2fd15.jpg)
![logo](https://user-images.githubusercontent.com/5215798/45819780-761dd780-bce5-11e8-84a4-4ab4e13d4046.png)
![m_text_squared](https://user-images.githubusercontent.com/5215798/45825768-4bd31680-bcf3-11e8-8b46-33a7b03ddf86.png)
![vizzuality_logo](https://user-images.githubusercontent.com/5215798/45833519-1afbdd00-bd05-11e8-99b4-1d0dc52f4087.png)

**Comment by ramiroaznar** [comment]
- [x] Faltaría meter a dotGIS y TYC GIS. 
- [x] Yo les daría un mínimo de padding.

![tyc_gis_formacion2](https://user-images.githubusercontent.com/5215798/45914817-b0ed5000-be4a-11e8-8220-d4d39684eb81.png)
![dotgis](https://user-images.githubusercontent.com/5215798/45914818-b0ed5000-be4a-11e8-99a8-cfff146c32d0.png)

**Comment by All4Gis** [comment]
Añadir iconos nuevos

![logoweb](https://user-images.githubusercontent.com/8123225/45951890-809de100-c005-11e8-8d85-71b3b385a549.jpg)


![logo-mapsens 1](https://user-images.githubusercontent.com/8123225/45951861-695ef380-c005-11e8-9ac6-ce891f70c367.png)
![tyc_gis_con_firma](https://user-images.githubusercontent.com/8123225/45951862-695ef380-c005-11e8-8d6c-dd0013b2be27.jpg)

**Comment by ramiroaznar** [comment]
@All4Gis TYC GIS is already on the web.

**Comment by ramiroaznar** [comment]
![incamedio](https://user-images.githubusercontent.com/5215798/46132915-9f87b780-c23f-11e8-8361-efe8259675e4.png)
![logoicarto](https://user-images.githubusercontent.com/5215798/46132925-a1517b00-c23f-11e8-85d3-6fd8e52a1ab4.png)

**Comment by ramiroaznar** [comment]
![unigis](https://user-images.githubusercontent.com/5215798/46285782-fc0b0f80-c57c-11e8-98aa-7f356d61e670.jpg)
