### ISSUE TITLE
Camisetas

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#15]
Lo que tenemos de momento es el diseño y que pondremos los logos de los patrocinadores (en la espalda supongo)

![](https://raw.githubusercontent.com/geocamp-es/2018/master/assets/img/camisetas/camiseta2018.png)

**Comment by jsanz** [comment]
@All4Gis @clds1 porfa actualizad con lo que tenéis claro de este tema (fechas, posibles proveedores, etc)

**Comment by All4Gis** [comment]
En la espalda se pondran los logos de los partners!Hoy subo el diseño

**Comment by clds1** [comment]
Tenemos presupuesto de 7colores en Colme. Para un logo delante. Pregunto cuanto por otro logo detrás.
He conseguido contactar con la empresa que me mandó Ramiro con la que trabaja CARTO.
Me mandan presupuesto y os digo.

**Comment by All4Gis** [comment]
![camiseta2018](https://user-images.githubusercontent.com/8123225/46213426-d2fa3d00-c338-11e8-94b5-805afe33bc7c.jpg)

**Comment by clds1** [comment]
Las vamos a pedir a ImaginePro. Blancas modelo BC E150 100% algodón (sin poliester). Para sesenta camisetas serían: de chicas, 2S, 10M y 3L; de chicos, 3S, 14M, 16L y 12XL. El presupuesto que nos han mandado es de 7,37€ cada una sin IVA,
Total; 535.06€
Si queréis que subamos el número de camisetas hasta setenta (chicas 3S, 12M y 3L; chicos 4S, 15M, 20L y 14XL) para tener de sobra, el total sería: 624.24€
Espero noticias y las imágenes a imprimir.

**Comment by ramiroaznar** [comment]
El último logo que @All4Gis tiene que encajar: ![unigis-logo-final](https://user-images.githubusercontent.com/5215798/46345209-00e6c680-c644-11e8-978f-eca455a2c006.png)

**Comment by ramiroaznar** [comment]
Al final no pusimos logos de patrocinadores.
