### ISSUE TITLE
Catering

### ISSUE THREAD

**Issue by clds1** [geocamp-es/2018#16]

**Comment by clds1** [comment]
Me han hablado de dos empresas de catering. AMAS Antojo y Artinale. Voy a informarme a ver. Además por la zona he visto otra que no está mal. Taberna Rayuela.
En cuanto tenga algo más concreto os digo.

**Comment by clds1** [comment]
he pedido presupuestos a AMAS y Artinale. Los primeros me han gustado mucho. Trabajan con discapacitados y potencian la integración social. Todo facilidades. Además sin plásticos y pueden llevar jarras para que tomemos agua de grifo, jejejeje. Los otros muy bien también pero más de andar por casa aunque se nota mucha experiencia a la hora de preguntarme cosas.
Habrá que ver ahora los presupuestos que lo mismo ni unos ni otros ;-P

**Comment by ramiroaznar** [comment]
El Rayuela fue todo un exito. +1 para proveedores locales
