### ISSUE TITLE
Asuntos pendientes

### ISSUE THREAD

**Issue by ramiroaznar** [geocamp-es/2018#18]
- [x] Subir sección de registro y añadir link al meetup https://www.meetup.com/es-ES/Geoinquietos-MAD/events/253172803/
- [x] Añadir mapa https://ramiroaznar.github.io/geocamp18-map/index.html
- [x] Centrar icono de GeoInquietos

**Comment by All4Gis** [comment]
Me pongo con ello en un rato!

**Comment by All4Gis** [comment]
Subido
