### ISSUE TITLE
Pegatinas

### ISSUE THREAD

**Issue by ramiroaznar** [geocamp-es/2018#19]
* Posiblemente se añadirán al pack de las camisetas https://github.com/geocamp-es/2018/issues/15
* Yo haría 100 de:

![geoinquietosmad](https://secure.meetupstatic.com/photos/event/1/8/b/4/600_439206324.jpeg)
(redonda)

![pulpo](https://pbs.twimg.com/profile_images/1021688521982177280/iWrgNenC_400x400.jpg)
(redonda)

![geocamp2018](https://github.com/geocamp-es/2018/blob/master/assets/img/LogoGeoCamp-minus.png?raw=true)
(rectangular)

**Comment by ramiroaznar** [comment]
![image](https://user-images.githubusercontent.com/5215798/46337771-b018a300-c62e-11e8-8ead-baa8c931364e.png)

**Comment by clds1** [comment]
Creo que las pegatinas redondas son un poco pequeñas. Yo haría la del pulpo de 2"x 2" y la de geoinquietos de 3" x 3" . Y añadiría chapas pequeñas (buttons) del pulpo de 1,5"x1,5".
Me parecen muchas de la geocamp, yo haría sólo las que tienen el año. Ese logo de Geocamp sólo va a servir para este año, el que viene será otro ¿y tendrá pulpo? jejeje
Van a sobrar un montón. Además habrá de algunos patrocinadores. Yo ajustaría. Al menos bajarlo a 80.

**Comment by ramiroaznar** [comment]
Siguiendo tus indicaciones, sale cuadrado el precio:

![image](https://user-images.githubusercontent.com/5215798/46340539-fa515280-c635-11e8-87d4-01af679cf1f0.png)

Yo de verdad no veo problema con las cantidades, sobrarán entre 10-20 que seguro que la gente cogerá la mayoría para amig@s.
