### ISSUE TITLE
Reunión Comunidad OpenStreetMap España

### ISSUE THREAD

**Issue by msevilla00** [geocamp-es/2018#2]
Traer aquí la idea de convocar a la comunidad OSM España aprovechando la GeoCamp y añadir la/s posible/s activida/es sobre esta temática.

**Comment by jsanz** [comment]
Te asigno la tarea @msevilla00, ¿cuáles serían las siguientes acciones?

**Comment by msevilla00** [comment]
Voy a contactar con la comunidad para ver si hay intención de venir pero en principio la idea es hacer una reunión general y quizá algún taller relacionado. Iré comentando por aquí.

**Comment by jsanz** [comment]
Perfecto, estaría bien saberlo pronto porque por ejemplo en Google Campus hay además del auditorio otro espacio para reunión que se podría solicitar y así tener las dos sesiones en paralelo

**Comment by jsanz** [comment]
Me refiero a **Café Planta 1**

![](https://lh3.googleusercontent.com/yTCyphWiSer9DwdAsDEBTmomwG4n09P-8ja4Dk2J1y54_uQRvXKj0gd8dtkOBy-a9hhFWV_N8v8lzV5tGBXIFWWIvw8=w1380-h920-p)

**Comment by msevilla00** [comment]
He anunciado hace unos días la iniciativa en la lista de correos de OSM-es / Talk-es:
https://lists.openstreetmap.org/pipermail/talk-es/2018-May/016105.html
A ver si caen más respuestas.

**Comment by msevilla00** [comment]
Acabo de volver a realizar recordatorio de la actividad. 
Estoy a la espera de si se suma alguna persona más para la organización.
Ahí está el mensaje que acabo de enviar a la lista de OSM-es:
https://lists.openstreetmap.org/pipermail/talk-es/2018-August/016267.html

**Comment by jsanz** [comment]
@msevilla00 qué tal con esta tarea? algo por hacer?

**Comment by msevilla00** [comment]
Acabo de enviar enlace del meetup a la lista de correos Talk-es de OSM para que la gente se apunte:
https://lists.openstreetmap.org/pipermail/talk-es/2018-September/016293.html
Y acabo de hacer referencia a este issue para la coordinación y/o para pensar ideas a trater en esta actividad.
https://lists.openstreetmap.org/pipermail/talk-es/2018-September/016294.html

**Comment by jsanz** [comment]
@msevilla00 al final cómo está el tema de OSM durante la reunión,? qué necesitáis?, qué tenéis pensado hacer? 

cc. @geocamp-es/2018

**Comment by msevilla00** [comment]
Mi idea era terminar de mover un pequeño "programa" con ideas a tratar a lo largo de estos días aquí.
Voy a volver a moverlo por la comunidad y escribo algo.

**Comment by msevilla00** [comment]
He vuelto a mandar mensaje a la lista y estoy evaluando la posibilidad entre los pocos asistentes de OSM que estaremos físicamente, abrir la sesión de manera remota. ¿Cómo va la red en ese lugar? @jsanz ?
En breve colgaré aquí un pequeño borrador de los temas que podríamos tratar.

**Comment by jsanz** [comment]
@ramiroaznar @clds1 la red en el MIL irá sobrada para hacer una sesión remota sobre OSM no? Seguimos contando con una sala para la gente de OSM no? 

Si tenemos un horario para esa sesión remota igual podemos pensar en darle a esa sala algún uso en plan para reuniones o sesiones ad-hoc que puedan surgir a lo largo del día, o directamente para algún pequeño taller (sobre HOT/OSM por ejemplo?)

**Comment by ramiroaznar** [comment]
> la red en el MIL irá sobrada para hacer una sesión remota sobre OSM no? 

Yo creo que si... 

> Seguimos contando con una sala para la gente de OSM no?

Hay una sala perfecta para reunirse.

**Comment by msevilla00** [comment]
¡Genial todo!
La cosa creo que no será de mucha gente pero si lo abrimos a remoto (tipo hangouts/jitsi) podemos tener cierta actividad.

**Comment by ramiroaznar** [comment]
Chapando esto. @msevilla00 espero que fuese productiva la reu!

**Comment by msevilla00** [comment]
Si, gracias, en breve habrá mensaje en la lista de la comunidad con lo que acordamos.
Un saludo
Miguel
