### ISSUE TITLE
Cambiar UNIGIS logo

### ISSUE THREAD

**Issue by ramiroaznar** [geocamp-es/2018#20]
Cambiar el logo actual de UNIGIS por este otro:

![unigis-logo-final 1](https://user-images.githubusercontent.com/5215798/46351033-a1de7d00-c656-11e8-92b2-f9a6e3e59eb2.png)

**Comment by jsanz** [comment]
he arreglado el orden para respetar el orden alfabético en ad57053c2fbd91f6d91eb0fd8cad49dd93bf860e
