### ISSUE TITLE
Web 2018

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#3]
Issue para gestionar la web para 2018

* [x] Copiar web 2017
* [ ] Adaptar textos
* [ ] ¿Cambios en estilos o secciones?

**Comment by All4Gis** [comment]
Subida web,a fala del mapa ,generar tienda etc!

**Comment by clds1** [comment]
Fran te dejo aquí el pdf de la geocamp_Es sponsor_pack actualizado para que lo enlaces en la web. He puesto un par de fotos de los madriles y he mantenido otras fotos del original. Revísalo antes por si se me ha pasado algo, please. Por ejemplo, el tipo de letra del logo de Geoinquietos Madrid que no sabía que poner ;-P
[geocampES_sponsor_pack_2018.pdf](https://github.com/geocamp-es/2018/files/2227866/geocampES_sponsor_pack_2018.pdf)

**Comment by clds1** [comment]
Enlaces que están mal dirigidos en la web:
GeoCamp 2012, abre una página en chino jajaja. 
Vigo 2013, abre la de A Coruña 2014. Cambiar por: http://2013.geocamp.es/
grupo Telegram, actualizar. Cambiar por: @GeoCamp - Madrid - 20 de Octubre
Geoinquietos Madrid, no carga la página. Cambiar por: http://geoinquietos.org/grupos/madrid/
Remember: quitar el enlace a Facebook.

....seguro que me dejo algo..... :)  :)  :)

**Comment by shiguera** [comment]
Está muy bien, aunque yo quizás especificaría, en donde pone 'Material 
Sponsor', aunque sea entre paréntesis, 'Guardia de Seguridad, limpieza 
del local cedido por el ayuntamiento', para que no parezca que nos lo 
gastamos todo en comida y en bebida

**Comment by clds1** [comment]
@shiguera te parece que lo defina como 'materiales, local y recursos necesarios', esto es más genérico para futuras geocamps y compila local, seguridad, limpieza, internet, etc,.. sin hacer un desglose tan específico.
Además, yo intercambiaría la cantidad de las contribuciones para material y goodie. Creo que queda mejor cara a la galería que se aporte más por los recursos necesarios para realizar la Geocamp que por los regalos. Osea, 200€ para material y 100€ para regalos, y no al revés
[geocampES_sponsor_pack_2018_def.pdf](https://github.com/geocamp-es/2018/files/2228189/geocampES_sponsor_pack_2018_def.pdf)
....

**Comment by shiguera** [comment]
Me parece muy bien

**Comment by All4Gis** [comment]
Corregido y subido @clds1

**Comment by clds1** [comment]
Thanks Fran. Un crac!!

Si mantenemos Facebook, habría que actualizar, al menos la foto del logo y el enlace a la web, jejejeje

**Comment by fpsampayo** [comment]
geocamp.es está redireccionado a 2018.geocamp.es. Cada año lo actualizo.
