### ISSUE TITLE
Registro DNS

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#4]
@fpsampayo esto me dice github en la página de configuración

>Your site's DNS settings are using a custom subdomain, 2018.geocamp.es, that's set up as an A record. We recommend you change this to a CNAME record pointing at [YOUR USERNAME].github.io. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/. 

Con un CNAME, además, podemos usar HTTPS lo cual siempre está bien.

¿Costaría mucho montar eso?

**Comment by fpsampayo** [comment]
Aprovecho y cambio todas a CNAME.

**Comment by fpsampayo** [comment]
@jsanz El cambio está listo, pero por algún motivo (permisos me imagino), github no me da la opción de cerrar esta issue. 
Me haría usted el favor?

**Comment by jsanz** [comment]
a sus :footprints:

**Comment by jsanz** [comment]
Mañana confirmo que el cambio funciona, ¡gracias!
