### ISSUE TITLE
Patrocinios

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#5]
* [x] Definir niveles, reutilizar material
  * Definir presupuestos de catering, camisetas, etc.
* [x] Buscar posibles patrocinadoers
* [x] Abrir ronda de contactos

**Comment by clds1** [comment]
En cuanto a los patrocinadores, estoy esperando contestación de Geomati.co (que lo van a hablar, osea no han dicho que no de entrada) y de Toni (Hidrólogo Geoinquieto) que está en la Fundación Botín, le he propuesto que se hagan cargo del gasto de jarras y vasos rellenables y quizá aporten para el resto de bebida-comida-cafés...

**Comment by clds1** [comment]
He creado un documentos para que vayamos poniendo los gastos e ingresos e ir haciendo balance.

**Comment by ramiroaznar** [comment]
### Patrocinadores

- CARTO
- dotGIS
- Geoblink
- Geographica
- geomati.co
- Inspide
- MappingGIS
- ServiGIS
- TYC GIS
- Paisaje Transversal
- Vizzuality
- Mapsens

**Comment by jsanz** [comment]
Cerramos esta issue no?
