### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by All4Gis** [geocamp-es/2018#7]
Generar mapa con el marcador del evento para embeberlo en la web

**Comment by jsanz** [comment]
@ramiroaznar yo creo que para esto podríamos hacer un mapa sencillo usando los vector tiles de CARTO y una chincheta apañada, o bien a lo mejor poner también las ediciones pasadas "detrás" y destacar la de 2018.

**Comment by jsanz** [comment]
tetes he estado ayudando a los de GUADEC con un mapa para el evento enteramente basado en datos de OSM. Esta es la [issue](https://gitlab.gnome.org/Community/Engagement/GUADEC/issues/50#note_247136) en la que lo hemos estado hablando.

Esto se puede reusar para la geocamp-es de arriba a abajo.

Lo podéis ver en acción [aquí](http://bl.ocks.org/jsanz/raw/1bc2f6a9c998fbc014bc1820dcb2c76d/). Ya me decís si os mola y lo metemos en la web directamente (sin iframe).

![2018-06-16_00 01 52-selection](https://user-images.githubusercontent.com/188264/41491295-850edeb2-70f8-11e8-999f-11233f066206.png)

**Comment by All4Gis** [comment]
esta bien!Si le puedes dar un poco más de estilo al pop-up mejor!good job

**Comment by jsanz** [comment]
Añadir también paradas de transporte públicos cercanos

**Comment by ramiroaznar** [comment]
### ETL
- [x] Extraer POIs de OSM:
  - [x] Transporte público:
    - [x] Paradas de autobuses: https://team.carto.com/u/ramirocartodb/dataset/geocamp_transport
      * https://team.carto.com/u/ramirocartodb/dataset/geocamp_buses
      * https://team.carto.com/u/ramirocartodb/dataset/geocamp_buses_aois
    - [x] BiciMad 
      * https://team.carto.com/u/ramirocartodb/dataset/geocamp_bicimad
      * https://team.carto.com/u/ramirocartodb/dataset/geocamp_bicimad_aois
    - [x] Paradas de metro https://team.carto.com/u/ramirocartodb/dataset/geocamp_metro
  - <strike>[ ] Bares y restaurantes
  - [ ] Lugares turísticos ("landmarks"): Mercado de la Cebada, Iglesia de SFco el Grande, Almudena, Palacio Real, Parque de las Vistillas, Parque de la Cornisa...
  - [ ] Hoteles y hostales</strike>
- [x] Localización de International Lab https://team.carto.com/u/ramirocartodb/dataset/geocamp_location
- [x] Hacer isocronas de 5-10 min andando https://team.carto.com/u/ramirocartodb/dataset/geocamp_aois

### svgs

* Metro https://upload.wikimedia.org/wikipedia/commons/e/ea/MetroMadridLogo.svg
* Bicimad https://upload.wikimedia.org/wikipedia/commons/9/95/Colombia_road_sign_SI-11.svg
* Bus https://upload.wikimedia.org/wikipedia/commons/4/44/MadridMetro-BusUrbano.svg

### Cartography
- [x] CARTO VL + gliphs + github pages

### Repo
- https://github.com/ramiroaznar/geocamp18-map
- https://ramiroaznar.github.io/geocamp18-map/index.html
