### ISSUE TITLE
Crear evento de registro y tienda para las camisetas

### ISSUE THREAD

**Issue by All4Gis** [geocamp-es/2018#8]
El registro puede ser un meetup.
La web de camisetas,darle una vuelta

**Comment by clds1** [comment]
Si queréis me encargo del meetup...

**Comment by clds1** [comment]
para las camisetas, quizá CARTO conozca de algún sitio...

**Comment by jsanz** [comment]
Borrador del Meetup creado

**Comment by clds1** [comment]
Hola chicos!
Según el calendario propuesto para los avisos de la Geocamp ya tendríamos que haberlo anunciado en listas de correo y grupos de redes. Y esta semana abrir la inscripción.
[https://docs.google.com/spreadsheets/d/1GMATGoDGnh-uznN-b6tjMozEWnHumOWWPioteE3HJXA/edit#gid=0](url)

Que os parece si al menos ya lo anunciamos oficialmente? y a primeros de la que viene abrimos la inscripción? Tenemos que hacernos una idea de la gente que se va a apuntar.

**Comment by clds1** [comment]
https://docs.google.com/spreadsheets/d/1GMATGoDGnh-uznN-b6tjMozEWnHumOWWPioteE3HJXA/edit#gid=0

**Comment by clds1** [comment]
Por otro lado, he confirmado el servicio de limpieza y he pedido presupuesto de seguridad (ya me han confirmado la empresa que lo hace) y también a una tienda de camisetas. Para irnos haciendo una idea.

**Comment by clds1** [comment]
La empresa de seguridad me acaba de mandar el presupuesto. Una pasta!! Lo incluyo en el doc de drive, pero si calculamos que el vigilante está de 9 a 20h, porque tendrá que abrir antes de que venga la gente y se tendrá que quedar hasta que  termine la señora de la limpieza.... son 16,62 x 11 = 182,82€ + iva

**Comment by jsanz** [comment]
cerramos esta y abrimos tema de camisetas en una issue nueva?

**Comment by clds1** [comment]
Sip
