### ISSUE TITLE
Definir formulario

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2018#9]
En el meetup vamos a llevar el control de asistencia, pero no da para hacer preguntas así que tocará crear un formulario externo y en el Meetup preguntar si se ha rellenado.

Esta tarea es para definir qué queremos preguntar y luego de qué forma.

### Preguntas

- si traen propuesta
- si quieren camiseta y talla
- si quieren el libro de Víctor
- si se quedarían a comer el sábado
- si se quedarían a cenar el viernes y el sábado
- si vendrían a una actividad el domingo
- alergias

### Implementación

* Google Forms?
* Typeform?

**Comment by clds1** [comment]
No he usado nunca ninguno de los dos. Pero por lo que he visto, Typeform me resulta más amigable.
Lo voy preparando si no me decís lo contrario....

**Comment by jsanz** [comment]
:+1: 

dale @clds1, si quieres puedes pasar por aquí pantallazos de cómo queda, igual podrías crear una cuenta genérica de geocamp en typeform para esto y así se puede compartir con actuales y futuros organizadores

**Comment by clds1** [comment]
vale

**Comment by clds1** [comment]
Para crear cuenta genérica en typeform necesito un mail y contraseña de geocampes. ¿Cuáles?

**Comment by clds1** [comment]
El typeform gratuito tiene algunas limitaciones. Voy a hacer lo que pueda... si vemos que al final no convence, tendremos que probar otras opciones. En breve os comparto!

**Comment by clds1** [comment]
https://geocampes.typeform.com/to/wSjVGU

Aquí está el formulario. La última actualización. Miradlo y me decís.
Como he dicho, al ser la versión gratuita está limitada, pero creo que no ha quedado mal.
- No deja hacer más de diez pantallas, así que si queréis incluir alguna cuestión más, hay que quitar una de las que están o agruparlas (de todas formas no es bueno hacer formularios demasiado largos, así no está mal).
- Tampoco permite hacer saltos, así que lo de las tallas de las camisetas lo he 'apañao' más o menos (no sé si da lugar a confusión).

He puesto que notifique a info@geocamp.es cada vez que se hace una inscripción para que todos nos enteremos, aunque no todos lo gestionemos.
He elegido el look pizarra de colegio porque me mola, pero se admiten sugerencias... pero sin complicaciones porfa (había pensado mejor un fondo de un mapa antiguo chulo en sepia pero no he encontrado...).
No he puesto nada de las posibles cenas....

Bueno, pues al toro!!!
Bss

**Comment by clds1** [comment]
Por supuesto comentarme lo que os parece la forma en que he enfocado en tema de los pagos. Yo creo que queda muy políticamente correcto, pero OJO tenéis que ir hasta el final del formulario para poder opinar.
Y después hay que pensar como hacer el pago (he puesto PayPal por poner algo y porque se comentó en algún momento) y yo no sé como enlazarlo al formulario. De nuevo, aunque Typeform permite incluir enlaces de pagos, al ser la versión gratuita no nos deja.
Ya me decís wapos!!

**Comment by jsanz** [comment]
Carmen la idea de inscripción que yo tenía era:

* Usamos Meetup para todo el tema de la difusión, explicar qué es la
conferencia, etc
* En meetup se puede hacer una pregunta. Ahí pedir a la gente que confirme
si ha rellenado el typeform.
* En meetup gestionar el cobro, que va inculído sin problema, así como la
lista de asistentes y demás.

Es decir le typeform es solo para recoger la info extra que en meetup no
nos deja sacar, vamos todo lo que has hecho está perfecto excepto que yo no
mencionaría nada del pago ahí.

¿Tiene sentido esto que planteo?

Para mí la pregunta 9 tampoco sería necesaria. Para qué vamos a gastar ese
dinero... pues para las cosas del evento y ya está no creo que sea buena
idea preguntar.

Respecto al aspecto... pues me da un poco igual, yo hubiera seguramente
usado algo más sencillo con los colores del evento (rojo, azul) y ya está,
pero la verdad es que así también está bien y no me parece que tenga mucha
más importancia.

Gracias por el curro!!!

**Comment by clds1** [comment]
Yo creo que visto que el tema del pago es controvertido, tanto el aviso primero de que hay que pagar una reserva como la pregunta 9, son importantes:
- El aviso es para dar la oportunidad de que si alguien no puede pagar contacte con nosotros y pueda asistir si realmente está interesado, sin que le de corte plantear la opción de no pagar.
- El tema de preguntar en que se va a gastar el dinero, es para plantear la opción de 'devolver el dinero' ya que la idea que a mi más me cuadra con este evento, es realizar el pago de la inscripción como una 'reserva de plaza' para asegurar la asistencia y no 'una entrada al evento'. Si en el formulario no nos piden la devolución, podemos contar con ese dinero para los gastos, sino yo lo devolvería. Es verdad que a lo mejor no hay que ser tan detallista, los gastos los he definido según el sponsor pack que cuelga de la web, así en realidad cada asistente puede ser un poco sponsor, al fin y al cabo tod@s tienen la posibilidad de salir al estrado a hacerse publicidad jejejeje

Pero esto se me ha ido ocurriendo para resolver de manera creo adecuada los posibles conflictos 'conceptuales' relacionados con el dinero y ponerlo fácil para que a quién no le importe pagar, lo haga y quién no pueda o no quiera, también pueda venir. Pero garantizando el interés y el compromiso en asistir.
De todas formas, habrá que confirmar unas cuantas veces la asistencia seguramente. Osea, seguimos con el calendario propuesto.

En cuanto a lo del Meetup, sí a todo. La difusión e información horaria, fechas, ubicación, número de asistentes, cobro, etc... yo también las haría por ahí.  La lista de asistentes también te la descargas con el formulario, con nombre y apellidos, que además necesitamos para entregarla en la puerta del MIL para el control de seguridad, así que tenemos las dos opciones  ;-P 

Y lo del pago, la verdad es que estoy desinformada, así que cómo mejor y más económico nos resulte. Si que creo que habría que pagar DESPUÉS de rellenar el formulario. Pero supongo que si en Meetup hay un enlace al formulario, después de acabarlo se vuelve al Meetup, no? y allí se paga, no? ¿cómo se hace esto?

Bueno estas son mis ideas. Ya os vais posicionando y vamos dándole forma al tema!
No puedo meteros como gestores del formulario porque de gratis no se puede, pero lo que me vayáis diciendo, lo voy cambiando.

Mañana me pongo con el Meetup (Ramiro help me please!!) y os cuento también.
Aprovechad las rebajas que la semana que viene vuelve mi jefeeeeeeee!!!!!!

**Comment by shiguera** [comment]
Hola:

Yo no he conseguido acceder al typeform, todavía.

Respecto del pago, mi opinión es que no hay que plantear devolver el 
dinero, se va a necesitar para el evento y, si alguno no quiere pagar 
por cabezonería, pues que no venga, no pasa nada. Al contrarío, yo 
pondría una opción de 'micro-suporter', para gente que no vaya a venir 
pero quiera ayudarnos con el importe de la entrada. A cambio podemos 
enviarle una camiseta y el resto de regalos que demos. No sé cuanto 
costaría el envío, la verdad. A lo mejor, en esos casos, hay que poner 
gastos de envío aparte. Yo, por ejemplo, en la última geocamp no fui, 
pero pagué la camiseta y me hizo mucha ilusión recibirla. Estoy seguro 
de que hay más gente en esa situación, que no va a venir pero le va a 
gustar hacer alguna aportación. Ya publicaremos de alguna manera la 
lista de gente que a aportado dinero para el evento. (Cuanto más lo 
releo, más me gusta la idea de los micro-supporters, igual había que 
pensar algo).

Yo no sería tan condescendiente con los que no quieren pagar por 
cabezonería. Los eventos no son 'gratis', cuestan dinero. El hecho de 
venir dos días a madrid es dinero para cualquier asistente, bastante más 
que lo de la entrada. La entrada se va a usar en agasajar a los 
asistentes, sea con comida, desayuno, camiseta o lo que sea, por lo que 
si no se cobra, también lo van a tener que gastar. Dudo que alguien que 
le cueste pagar el importe de la entrada, se pueda permitir estar dos 
días en Madrid para el evento. Por supuesto, si alguien tiene 
dificultades, mi opinión es que no tenga que pagar o, incluso, poder 
ayudarle con los gastos de estancia y demás. Pero los que no quieren 
pagar por cabezonería, por una especie de 'principios', en mi opinión, 
en el fondo están siendo unos talibanes que no merecen mi comprensión. 
Mucho menos cuando alguno amenaza en plan chantaje: 'si se cobra la 
entrada yo no voy'. La respuesta que me suele salir automática en esos 
caso es : 'Pues no vengas, no te preocupes, sobreviviremos sin ti'. En 
algunos casos no les importa en absoluto gastarse una pasta en otros 
eventos.

En fin, no quiero hacer más sangre. Un saludo

Santiago Higuera

**Comment by clds1** [comment]
Dale Santiago!!!
Pues tu voto ya lo tenemos, parece que hay mayoría al 'si pagar'. Así que quito el punto 9. Os mando el formulario tal como llegaría a los que quieren inscribirse. Algún cambio más que se os ocurra?

**Comment by clds1** [comment]
Si queréis probar a rellenarlo estaría bien y así veo como se gestionan las respuestas que llegan...

**Comment by clds1** [comment]
La nota que había al principio:
'NOTA IMPORTANTE: el local donde se va a desarrollar la Geocamp tiene un aforo limitado por lo que para inscribirte tienes que hacer una reserva de 5€ a través de PayPal y así asegurar tu asistencia. Si estás dispuesto a ello, continúa con el registro, sino por favor escríbenos a info@geocamp.es para tratar de gestionar tu inscripción'

Se puede poner en el Meetup para informar a la gente del pago

**Comment by michogar** [comment]
@shiguera creo que nos debemos unas cervezas y hablar este tema en persona. Estuvimos hablando con @clds1 en Guimaraes y creo que transmitimos nuestra opinión y pienso que es respetable. Todo lo demás es troleo y así hay que entenderlo, ni me planteo no ir, ni hacer ningún tipo de acto para boicotear, ni nada parecido. Siento si no se han entendido los mensajes y os pido disculpas por el ruido que haya podido generar. El tema para mi es importante y soy enérgico cuando discuto sobre temas que me importan, pero no me cosidero un talibán.

Este año es vuestro geocamp y lo haréis como vosotros consideréis, lo mio es solo opinión y debate. Creo que @clds1 puede confirmarte en persona lo que hablamos y cual era mi tono. Y si no se ha entendido vuelvo a pediros disculpas.

Un abrazo y mucho ánimo.

**Comment by clds1** [comment]
Tranquilo @michogar creo que por aquí tod@s sabemos que estamos en el mismo barco... pero nos encanta la polémica!!! jejeje y @shiguera es un hueso duro de roer y sin pelos en la lengua  ;-P 
Yo me apunto al debate y las cañas con vosotros!! Bss

**Comment by shiguera** [comment]
Gracias, Micho, hablaremos y tomaremos esas cervezas

**Comment by shiguera** [comment]
Creo que habría que poner 10 euros

**Comment by shiguera** [comment]
Sigo sin saber cómo se accede

**Comment by clds1** [comment]
@shiguera No te ha llegado un mail de GEOCAMPes con el asunto de tomarte un momento para rellenar el formulario?

**Comment by shiguera** [comment]
Yo creo que no, pero volveré a mirar mejor

**Comment by damateos** [comment]
Hola,

no sé lo que habia comentado Micho previamente, pero yo también discrepo con Santi (y parece que con más gente) sobre el tema de los pagos.  Supongo que venimos de experiencias diferentes en el mundo de la autogestión. Pero vamos, sólo por dejar de manifiesto que hay distintas sensibilidades con el tema, y que posiblemente le tendríamos que haber dedicado un rato a discutirlo en las oportunidades en que nos hemos visto.
Sin más, tampoco voy a entrar a una discusión por aquí y me apunto a las cañas (nos vamos a dejar más en cañas para discutir, que en la entrada)

**Comment by clds1** [comment]
Hola Dani,
este tema se ha discutido bastante en el grupo de telegram, por eso te han llegado por aquí sólo los últimos coletazos jeje
Ha habido mucho debate, pero la mayoría del comité de GeocamMadrid cree que es mejor cobrar una entrada para garantizar la asistencia (4 sobre 6).
En todo caso es un buen tema a discutir con las cañas ;-P

**Comment by clds1** [comment]
Aquí dejo el enlace al formulario con los cambios sugeridos.
He cambiado la foto del libro de @Volaya según la que aparece en Amazon, que entiendo es la correcta, aún así le he preguntado a Víctor, a ver si me contesta.
He puesto en lo de las camisetas: 'selecciona modelo y talla, por favor' que creo contempla todas las sugerencias ;-P
Ya me diréis....

 https://geocampes.typeform.com/to/S4jZId

**Comment by clds1** [comment]
Enlace al formulario actualizado para el meetup

https://geocampes.typeform.com/to/S4jZId
